### ISSUE TITLE
Request go.plugin-settings.get-configuration is not supported by plugin

### ISSUE THREAD

**Issue by derfred** [gocd-contrib/github-oauth-authorization-plugin#214]
I have installed the extension according to the instructions in INSTALL.md. After saving the config for the auth plugin I get this error:
```
There was a problem fetching Authorization Configurations

Refresh [this page](javascript: window.location.reload()) in some time, and if the problem persists, check the server logs.
```

The logs show:
```
jvm 1    | 2022-06-15 15:56:26,054 INFO  [Thread-78] DefaultPluginJarChangeListener:67 - Plugin load starting: /go-working-dir/plugins/external/githubauth.jar
jvm 1    | 2022-06-15 15:56:26,356  WARN [Thread-78] p.c.g.a.g.c.g.a.g.GitHubPlugin:97 [plugin-cd.go.authorization.github] - Request go.plugin-settings.get-configuration is not supported by plugin.
jvm 1    | 2022-06-15 15:56:26,357 WARN  [Thread-78] PluginSettingsMetadataLoader:63 - Failed to fetch plugin settings metadata for plugin cd.go.authorization.github. Maybe the plugin does not implement plugin settings and view?
jvm 1    | 2022-06-15 15:56:26,357 WARN  [Thread-78] PluginSettingsMetadataLoader:64 - Plugin: cd.go.authorization.github - Metadata load info: [{extension='authorization', configuration='null', view='null', error='The plugin sent a null response'}]
jvm 1    | 2022-06-15 15:56:26,358 WARN  [Thread-78] PluginSettingsMetadataLoader:65 - Not all plugins are required to implement the request above. This error may be safe to ignore.
jvm 1    | 2022-06-15 15:56:26,358 INFO  [Thread-78] DefaultPluginJarChangeListener:74 - Plugin load finished: /go-working-dir/plugins/external/githubauth.jar
```

And when I try to login I get:
```
jvm 1    | 2022-06-15 16:00:37,273 ERROR [qtp856469860-24] p.c.g.a.g.c.g.a.g.GitHubPlugin:127 [plugin-cd.go.authorization.github] - Error while executing request go.cd.authorization.fetch-access-token
jvm 1    | java.lang.IllegalArgumentException: Get Access Token] Expecting `code` in request params, but not received.
jvm 1    | 	at cd.go.authorization.github.executors.FetchAccessTokenRequestExecutor.execute(FetchAccessTokenRequestExecutor.java:51)
jvm 1    | 	at cd.go.authorization.github.requests.Request.execute(Request.java:47)
jvm 1    | 	at cd.go.authorization.github.GitHubPlugin.handle(GitHubPlugin.java:69)
```

I'm running the official docker image `gocd/gocd-server:v22.1.0` and installed the plugin using `-e GOCD_PLUGIN_INSTALL_githubauth=https://github.com/gocd-contrib/github-oauth-authorization-plugin/releases/download/v3.3.0-172/github-oauth-authorization-plugin-3.3.0-172.jar`

**Comment by chadlwilson** [comment]
Can you please
* include the information from the plugin-specific log file in your server `logs` folder?
* include a redacted version of the configuration saved for the plugin? If you look at `Admin > Config XML` and extract+redact just the `<authConfig>` with  `pluginId="cd.go.authorization.github"` that'd help. If you can't load the Authorization Configurations page, it doesn't seem very promising that the plugin will work.

The above seems to be missing the error that corresponds with `There was a problem fetching Authorization Configurations` which is probably what needs to be figured out first, I imagine.
